spring:
  application:
    name: sensor-readings-service
  datasource:
    url: jdbc:postgresql://localhost:5432/avimax
    username: ${DB_USERNAME:avimax}
    password: ${DB_PASSWORD:avimax}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
